name: Build Android

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup Godot
        # You may pin to the exact commit or the version.
        # uses: Vitorgus/Setup-Godot@74955da65a6ceea4a391a5e70b3c24297475acaf
        uses: Vitorgus/Setup-Godot@v1.1.1
        with:
          # Godot version to download
          godot-version: 
          # If set to true, will download de mono version of Godot
          mono: # optional
          # If set to false, will skip the default export templates download
          download-templates: # optional, default is true

      - name: Install Android Build Template
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.2.2.stable
          wget https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz
          unzip Godot_v4.2.2-stable_export_templates.tpz -d templates
          mv templates/templates/* ~/.local/share/godot/export_templates/4.2.2.stable/

      - name: Build C# project
        run: dotnet build src/STS2Mobile/STS2Mobile.csproj

      - name: Export Android
        run: |
          "$GODOT_BIN" \
            --headless \
            --export-release Android build.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build.apk
